apiVersion: v1
kind: Service
metadata:
  name: external-redis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-redis
subsets:
  - addresses:
      - ip: 35.195.14.220
    ports:
      - port: 6379
