apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: eu.gcr.io/ultra-envoy-264613/flask-app:latest
        env:
        - name: DB_PASSWORD
          value: supersecure
        # - name: REDIS_NAME
        #   value: redis-service
        - name: REDIS_NAME
          value: external-redis
        - name: DB_NAME
          value: mysql-service
        ports:
          - containerPort: 80
